"use client";

import * as LabelPrimitive from "@radix-ui/react-label";
import * as SwitchPrimitive from "@radix-ui/react-switch";
import { Check, ChevronDown, Star } from "lucide-react";
import * as React from "react";

import { cn } from "@/lib/utils";

/* -------------------------------------------------------------------------- */
/* Field wrapper — label, control, hint and error in the right order         */
/* -------------------------------------------------------------------------- */

interface FieldContextValue {
  id: string;
  invalid: boolean;
  describedBy?: string;
}

const FieldContext = React.createContext<FieldContextValue | null>(null);

export function Field({
  label,
  hint,
  error,
  required,
  className,
  children,
}: {
  label?: React.ReactNode;
  hint?: React.ReactNode;
  error?: string | string[] | null;
  required?: boolean;
  className?: string;
  children: React.ReactNode;
}) {
  const id = React.useId();
  const messages = Array.isArray(error) ? error : error ? [error] : [];
  const invalid = messages.length > 0;
  const hintId = hint && !invalid ? `${id}-hint` : undefined;
  const errorId = invalid ? `${id}-error` : undefined;
  const describedBy = [hintId, errorId].filter(Boolean).join(" ") || undefined;

  return (
    <FieldContext.Provider value={{ id, invalid, describedBy }}>
      <div className={cn("space-y-1.5", className)}>
        {label ? (
          <LabelPrimitive.Root
            htmlFor={id}
            className="block text-sm font-medium text-fg peer-disabled:opacity-60"
          >
            {label}
            {required ? (
              <span className="ml-0.5 text-danger" aria-hidden>
                *
              </span>
            ) : null}
          </LabelPrimitive.Root>
        ) : null}
        {children}
        {hint ? (
          <p id={hintId} className="text-xs text-fg-subtle">
            {hint}
          </p>
        ) : null}
        {invalid ? (
          <p id={errorId} role="alert" className="text-xs font-medium text-danger">
            {messages[0]}
          </p>
        ) : null}
      </div>
    </FieldContext.Provider>
  );
}

/* -------------------------------------------------------------------------- */
/* Shared control styling                                                     */
/* -------------------------------------------------------------------------- */

const controlBase = [
  "w-full rounded-[var(--radius-control)] border bg-surface px-3.5 text-sm text-fg",
  "placeholder:text-fg-subtle",
  "transition-[border-color,box-shadow,background-color] duration-[var(--duration-fast)]",
  "disabled:cursor-not-allowed disabled:opacity-60",
].join(" ");

const controlState = (invalid: boolean) =>
  invalid
    ? "border-danger focus-visible:border-danger"
    : "border-border hover:border-border-strong focus-visible:border-brand";

/* -------------------------------------------------------------------------- */
/* Input                                                                      */
/* -------------------------------------------------------------------------- */

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  /** Overrides the id generated by the enclosing <Field>. */
  id?: string;
  invalid?: boolean;
  leadingIcon?: React.ReactNode;
  trailingSlot?: React.ReactNode;
}

export const Input = React.forwardRef<HTMLInputElement, InputProps>(function Input(
  { className, id, invalid, leadingIcon, trailingSlot, ...props },
  ref,
) {
  const field = React.useContext(FieldContext);
  const controlId = id ?? field?.id;
  const isInvalid = invalid ?? field?.invalid ?? false;
  const describedBy = field?.describedBy;

  if (!leadingIcon && !trailingSlot) {
    return (
      <input
        ref={ref}
        id={controlId}
        aria-invalid={isInvalid || undefined}
        aria-describedby={describedBy}
        className={cn(controlBase, controlState(isInvalid), "h-11", className)}
        {...props}
      />
    );
  }

  return (
    <div className="relative">
      {leadingIcon ? (
        <span className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-fg-subtle [&_svg]:size-4">
          {leadingIcon}
        </span>
      ) : null}
      <input
        ref={ref}
        id={controlId}
        aria-invalid={isInvalid || undefined}
        aria-describedby={describedBy}
        className={cn(
          controlBase,
          controlState(isInvalid),
          "h-11",
          leadingIcon && "pl-10",
          trailingSlot && "pr-11",
          className,
        )}
        {...props}
      />
      {trailingSlot ? (
        <span className="absolute right-2 top-1/2 -translate-y-1/2">{trailingSlot}</span>
      ) : null}
    </div>
  );
});

/* -------------------------------------------------------------------------- */
/* Textarea                                                                   */
/* -------------------------------------------------------------------------- */

export interface TextareaProps extends React.TextareaHTMLAttributes<HTMLTextAreaElement> {
  invalid?: boolean;
}

export const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(function Textarea(
  { className, id, invalid, ...props },
  ref,
) {
  const field = React.useContext(FieldContext);
  return (
    <textarea
      ref={ref}
      id={id ?? field?.id}
      aria-invalid={(invalid ?? field?.invalid) || undefined}
      aria-describedby={field?.describedBy}
      className={cn(
        controlBase,
        controlState(invalid ?? field?.invalid ?? false),
        "min-h-24 resize-y py-2.5 leading-relaxed",
        className,
      )}
      {...props}
    />
  );
});

/* -------------------------------------------------------------------------- */
/* Select                                                                     */
/* -------------------------------------------------------------------------- */

export interface SelectOption {
  value: string;
  label: string;
}

export function Select({
  options,
  id,
  invalid,
  className,
  placeholder,
  ...props
}: Omit<React.SelectHTMLAttributes<HTMLSelectElement>, "children"> & {
  options: SelectOption[];
  id?: string;
  invalid?: boolean;
  placeholder?: string;
}) {
  const field = React.useContext(FieldContext);
  return (
    <div className="relative">
      <select
        id={id ?? field?.id}
        aria-invalid={(invalid ?? field?.invalid) || undefined}
        aria-describedby={field?.describedBy}
        className={cn(
          controlBase,
          controlState(invalid ?? field?.invalid ?? false),
          "h-11 cursor-pointer appearance-none pr-10",
          className,
        )}
        {...props}
      >
        {placeholder ? (
          <option value="" disabled>
            {placeholder}
          </option>
        ) : null}
        {options.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
      <ChevronDown
        className="pointer-events-none absolute right-3 top-1/2 size-4 -translate-y-1/2 text-fg-subtle"
        aria-hidden
      />
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/* Switch                                                                     */
/* -------------------------------------------------------------------------- */

export const Switch = React.forwardRef<
  React.ComponentRef<typeof SwitchPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof SwitchPrimitive.Root>
>(function Switch({ className, ...props }, ref) {
  return (
    <SwitchPrimitive.Root
      ref={ref}
      className={cn(
        "peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent",
        "transition-colors duration-[var(--duration-base)] ease-[var(--ease-standard)]",
        "data-[state=checked]:bg-brand data-[state=unchecked]:bg-border-strong",
        "disabled:cursor-not-allowed disabled:opacity-50",
        className,
      )}
      {...props}
    >
      <SwitchPrimitive.Thumb
        className={cn(
          "pointer-events-none block size-5 rounded-full bg-surface shadow-sm ring-0",
          "transition-transform duration-[var(--duration-base)] ease-[var(--ease-standard)]",
          "data-[state=checked]:translate-x-5 data-[state=unchecked]:translate-x-0",
        )}
      />
    </SwitchPrimitive.Root>
  );
});

/* -------------------------------------------------------------------------- */
/* Star rating (display + input)                                              */
/* -------------------------------------------------------------------------- */

export function RatingStars({
  value,
  size = 16,
  className,
}: {
  value: number;
  size?: number;
  className?: string;
}) {
  return (
    <span className={cn("inline-flex items-center gap-0.5", className)} aria-hidden>
      {[1, 2, 3, 4, 5].map((star) => (
        <Star
          key={star}
          style={{ width: size, height: size }}
          className={cn(
            star <= Math.round(value) ? "fill-rating text-rating" : "text-border-strong",
          )}
        />
      ))}
    </span>
  );
}

export function RatingInput({
  value,
  onChange,
  max = 5,
  name,
  className,
}: {
  value: number;
  onChange: (value: number) => void;
  max?: number;
  name?: string;
  className?: string;
}) {
  const [hovered, setHovered] = React.useState<number | null>(null);
  const shown = hovered ?? value;

  return (
    <div
      className={cn("inline-flex items-center gap-1", className)}
      role="radiogroup"
      onMouseLeave={() => setHovered(null)}
    >
      {Array.from({ length: max }, (_, index) => index + 1).map((star) => {
        const active = star <= shown;
        return (
          <button
            key={star}
            type="button"
            role="radio"
            aria-checked={star === value}
            aria-label={`${star}`}
            name={name}
            className={cn(
              "rounded p-0.5 transition-transform duration-[var(--duration-instant)]",
              "hover:scale-110 active:scale-95",
            )}
            onMouseEnter={() => setHovered(star)}
            onFocus={() => setHovered(star)}
            onBlur={() => setHovered(null)}
            onClick={() => onChange(star)}
          >
            <Star
              className={cn(
                "size-6 transition-colors duration-[var(--duration-instant)]",
                active ? "fill-rating text-rating" : "text-border-strong",
              )}
            />
          </button>
        );
      })}
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/* Checkbox row                                                               */
/* -------------------------------------------------------------------------- */

export function CheckboxRow({
  id,
  checked,
  onCheckedChange,
  label,
  description,
  className,
}: {
  id: string;
  checked: boolean;
  onCheckedChange: (checked: boolean) => void;
  label: React.ReactNode;
  description?: React.ReactNode;
  className?: string;
}) {
  return (
    <label
      htmlFor={id}
      className={cn(
        "flex cursor-pointer items-start gap-3 rounded-[var(--radius-control)] p-2.5",
        "transition-colors duration-[var(--duration-fast)] hover:bg-surface-hover",
        className,
      )}
    >
      <span className="relative mt-0.5 flex size-5 shrink-0 items-center justify-center">
        <input
          id={id}
          type="checkbox"
          checked={checked}
          onChange={(event) => onCheckedChange(event.target.checked)}
          className="peer size-5 cursor-pointer appearance-none rounded-[5px] border border-border-strong bg-surface transition-colors checked:border-brand checked:bg-brand"
        />
        <Check
          className="pointer-events-none absolute size-3.5 text-fg-inverse opacity-0 peer-checked:opacity-100"
          aria-hidden
        />
      </span>
      <span className="min-w-0">
        <span className="block text-sm font-medium text-fg">{label}</span>
        {description ? (
          <span className="block text-xs text-fg-muted">{description}</span>
        ) : null}
      </span>
    </label>
  );
}
