"""Seed content for FintFood.

Reusable data structures used by the ``seed_data`` management command.
Names follow a single canonical spelling; the command normalizes them.
"""

INGREDIENT_CATEGORIES = [
    "Vegetables",
    "Meat",
    "Chicken",
    "Fish",
    "Dairy",
    "Eggs",
    "Grains",
    "Fruits",
    "Spices",
    "Other",
]

# name -> category slug (canonical ingredients)
INGREDIENTS = {
    # Vegetables
    "Potato": "vegetables",
    "Onion": "vegetables",
    "Carrot": "vegetables",
    "Tomato": "vegetables",
    "Cucumber": "vegetables",
    "Bell Pepper": "vegetables",
    "Garlic": "vegetables",
    "Cabbage": "vegetables",
    "Spinach": "vegetables",
    "Zucchini": "vegetables",
    "Eggplant": "vegetables",
    "Pumpkin": "vegetables",
    "Radish": "vegetables",
    "Sweet Corn": "vegetables",
    "Mushroom": "vegetables",
    "Broccoli": "vegetables",
    "Lettuce": "vegetables",
    "Green Beans": "vegetables",
    "Leek": "vegetables",
    "Celery": "vegetables",
    "Peas": "vegetables",
    "Chili Pepper": "vegetables",
    # Meat
    "Beef": "meat",
    "Lamb": "meat",
    "Pork": "meat",
    "Ground Beef": "meat",
    "Beef Brisket": "meat",
    "Bacon": "meat",
    "Chicken Liver": "meat",
    # Chicken
    "Chicken": "chicken",
    "Chicken Thighs": "chicken",
    "Chicken Breast": "chicken",
    "Chicken Wings": "chicken",
    "Chicken Drumsticks": "chicken",
    # Fish
    "Fish": "fish",
    "Salmon": "fish",
    "Mackerel": "fish",
    "White Fish Fillet": "fish",
    "Shrimp": "fish",
    # Dairy
    "Milk": "dairy",
    "Butter": "dairy",
    "Cheddar Cheese": "dairy",
    "Cream": "dairy",
    "Yogurt": "dairy",
    "Sour Cream": "dairy",
    "Mozzarella": "dairy",
    "Parmesan": "dairy",
    "Feta": "dairy",
    "Cream Cheese": "dairy",
    # Eggs
    "Egg": "eggs",
    # Grains
    "Rice": "grains",
    "Flour": "grains",
    "Pasta": "grains",
    "Bread": "grains",
    "Noodles": "grains",
    "Couscous": "grains",
    "Buckwheat": "grains",
    "Oats": "grains",
    "Lavash": "grains",
    "Risotto Rice": "grains",
    "Lentils": "grains",
    "Chickpeas": "grains",
    "Spaghetti": "grains",
    "Pizza Dough": "grains",
    "Burger Buns": "grains",
    # Fruits
    "Lemon": "fruits",
    "Apple": "fruits",
    "Orange": "fruits",
    "Banana": "fruits",
    "Pomegranate": "fruits",
    "Grapes": "fruits",
    "Dried Apricots": "fruits",
    "Raisins": "fruits",
    "Dates": "fruits",
    "Strawberries": "fruits",
    "Blueberries": "fruits",
    "Avocado": "fruits",
    # Spices
    "Salt": "spices",
    "Black Pepper": "spices",
    "Vegetable Oil": "spices",
    "Olive Oil": "spices",
    "Sugar": "spices",
    "Paprika": "spices",
    "Turmeric": "spices",
    "Ground Cumin": "spices",
    "Ground Coriander": "spices",
    "Cinnamon": "spices",
    "Ginger": "spices",
    "Parsley": "spices",
    "Dill": "spices",
    "Cilantro": "spices",
    "Mint": "spices",
    "Bay Leaf": "spices",
    "Vinegar": "spices",
    "Soy Sauce": "spices",
    "Tomato Paste": "spices",
    "Honey": "spices",
    "Oregano": "spices",
    "Rosemary": "spices",
    "Thyme": "spices",
    "Basil": "spices",
    "Cocoa Powder": "spices",
    "Zira (Cumin Seeds)": "spices",
    "Chicken Broth": "other",
    "Beef Broth": "other",
    "Water": "other",
    "Walnuts": "other",
    "Sesame Seeds": "other",
    "Baking Powder": "other",
    "Vanilla Extract": "other",
    "Yeast": "other",
    "Heavy Cream": "other",
    "Tomato Sauce": "other",
    "Mayonnaise": "other",
    "Ketchup": "other",
    "Curry Powder": "spices",
    "Tahini": "other",
    "Espresso": "other",
    "Coconut Milk": "other",
    "Savoiardi Biscuits": "other",
    "Red Wine": "other",
    "Beetroot": "vegetables",
}

CATEGORIES = [
    ("Breakfast", "Wake up with hearty morning meals made from simple ingredients."),
    ("Lunch", "Light, satisfying midday dishes for busy schedules."),
    ("Dinner", "Hearty dinners for the whole family."),
    ("Desserts", "Sweet endings вЂ” cakes, pies, tarts and treats."),
    ("Soups", "Warming broths, borscht and creamy soups."),
    ("Salads", "Fresh, crunchy and vibrant salads."),
    ("Fast Food", "Quick shawarma, burgers and street-style favorites."),
    ("Uzbek Cuisine", "Timeless dishes of Central Asia вЂ” plov, manti, lagman and more."),
    ("Baking", "Breads, pastries and oven-baked goods."),
    ("Vegetarian", "Meat-free mains and sides that everyone will love."),
    ("Meat Dishes", "Beef, lamb and poultry mains cooked with care."),
    ("Poultry", "Chicken and turkey dishes from around the world."),
    ("Seafood", "Salmon, shrimp and fresh-catch recipes."),
    ("Appetizers", "Starters and snacks for sharing."),
    ("Drinks", "Homemade drinks, smoothies and compotes."),
]

# (title, category, cooking_min, prep_min, servings, difficulty, calories, protein, carbs, fat, ingredients, steps)
RECIPES = [
    (
        "Classic Uzbek Plov",
        "uzbek-cuisine",
        60, 20, 6, "medium", 540, 18, 62, 24,
        [("Rice", 500, "g"), ("Beef", 400, "g"), ("Carrot", 300, "g"), ("Onion", 2, "pcs"),
         ("Garlic", 1, "pcs"), ("Vegetable Oil", 150, "ml"), ("Salt", 2, "tsp"),
         ("Zira (Cumin Seeds)", 1, "tsp"), ("Water", 700, "ml")],
        [
            "Heat the oil in a heavy cast-iron pot (kazan) over medium-high heat.",
            "Add the beef cut into small cubes and fry until golden brown on all sides.",
            "Add thinly sliced onion and cook until translucent, stirring often.",
            "Add the carrot cut into matchsticks and fry together for 5 minutes.",
            "Pour in the water, add salt, zira and the whole head of garlic, simmer 15 minutes.",
            "Wash the rice thoroughly, spread it evenly over the zirvak and add more water to cover by 2 cm.",
            "Cover and cook on low heat for 20 minutes, then open, mix gently and serve hot.",
        ],
    ),
    (
        "Juicy Manti",
        "uzbek-cuisine",
        40, 60, 4, "hard", 460, 24, 48, 18,
        [("Flour", 500, "g"), ("Ground Beef", 500, "g"), ("Onion", 3, "pcs"),
         ("Salt", 2, "tsp"), ("Black Pepper", 1, "tsp"), ("Water", 250, "ml"), ("Butter", 50, "g")],
        [
            "Mix flour, a pinch of salt and water into a stiff dough, knead 10 minutes and rest for 30.",
            "For the filling, combine minced beef, finely chopped onion, salt and pepper.",
            "Roll the dough thin, cut into 8-10 cm squares and place a spoon of filling in each.",
            "Pinch the edges to form small pouches with tight seams.",
            "Grease the manti steamer (manti-kaskan) tiers with oil and arrange the manti.",
            "Steam over boiling water for 35-40 minutes until the dough is glossy and cooked.",
            "Serve with sour cream and fresh dill.",
        ],
    ),
    (
        "Lagman with Beef",
        "uzbek-cuisine",
        45, 40, 5, "medium", 420, 22, 52, 14,
        [("Noodles", 400, "g"), ("Beef", 350, "g"), ("Onion", 2, "pcs"), ("Bell Pepper", 2, "pcs"),
         ("Carrot", 1, "pcs"), ("Tomato", 2, "pcs"), ("Garlic", 3, "pcs"), ("Vegetable Oil", 60, "ml"),
         ("Soy Sauce", 2, "tbsp"), ("Salt", 1, "tsp"), ("Black Pepper", 0.5, "tsp"),
         ("Cilantro", 1, "bunch")],
        [
            "Cut beef into thin strips and fry in hot oil until browned.",
            "Add onion in half-rings, then julienned carrot and bell pepper, stir-frying each addition.",
            "Add diced tomatoes, chopped garlic, soy sauce and a splash of water; simmer the sauce 10 minutes.",
            "Boil noodles until just tender, then drain and rinse with cool water.",
            "Serve noodles in deep bowls, ladle the hot sauce over and garnish with fresh cilantro.",
        ],
    ),
    (
        "Dimlama (Steamed Meat and Vegetables)",
        "uzbek-cuisine",
        90, 25, 6, "medium", 380, 20, 30, 20,
        [("Beef", 600, "g"), ("Potato", 4, "pcs"), ("Carrot", 2, "pcs"), ("Onion", 2, "pcs"),
         ("Cabbage", 300, "g"), ("Bell Pepper", 2, "pcs"), ("Tomato", 3, "pcs"), ("Garlic", 4, "pcs"),
         ("Zira (Cumin Seeds)", 1, "tsp"), ("Salt", 2, "tsp"), ("Water", 200, "ml")],
        [
            "Layer the kazan: beef chunks first, then onion rings, carrot, potato, pepper, tomato and cabbage.",
            "Season each layer with salt and zira and stud with garlic cloves.",
            "Add a cup of water, cover tightly and steam over low heat for 60-80 minutes.",
            "When the vegetables are tender, stir everything gently to combine the juices.",
            "Serve on a big platter with warm flatbread.",
        ],
    ),
    (
        "Mastava (Rice Soup)",
        "uzbek-cuisine",
        40, 15, 4, "easy", 260, 12, 38, 6,
        [("Rice", 150, "g"), ("Beef", 200, "g"), ("Carrot", 1, "pcs"), ("Onion", 1, "pcs"),
         ("Tomato", 1, "pcs"), ("Potato", 1, "pcs"), ("Vegetable Oil", 20, "ml"), ("Salt", 1, "tsp"),
         ("Parsley", 1, "bunch")],
        [
            "Fry diced beef in oil until the moisture evaporates and the meat browns.",
            "Add onion, carrot and tomato, cook 5 minutes over medium heat.",
            "Add potatoes, washed rice and 1.5 liters of hot water; bring to a boil.",
            "Simmer gently for 25 minutes until the rice is soft and the soup thickens slightly.",
            "Season, pour into bowls and sprinkle with chopped parsley.",
        ],
    ),
    (
        "Somsa with Meat",
        "uzbek-cuisine",
        35, 45, 6, "medium", 480, 17, 55, 21,
        [("Flour", 500, "g"), ("Butter", 150, "g"), ("Ground Beef", 400, "g"), ("Onion", 3, "pcs"),
         ("Salt", 1.5, "tsp"), ("Black Pepper", 1, "tsp"), ("Egg", 1, "pcs"), ("Sesame Seeds", 1, "tsp"),
         ("Water", 150, "ml")],
        [
            "Rub butter into the flour, add water and knead into a soft dough; rest it for 30 minutes.",
            "Mix minced beef with finely chopped onion, salt and black pepper.",
            "Roll the dough, cut into circles and place a spoonful of filling in the center.",
            "Fold into triangles and pinch the seams tightly.",
            "Brush with beaten egg, sprinkle with sesame seeds and bake at 200В°C for 35 minutes.",
        ],
    ),
    (
        "Chuchvara (Uzbek Dumpling Soup)",
        "uzbek-cuisine",
        30, 50, 5, "medium", 350, 18, 42, 12,
        [("Flour", 400, "g"), ("Ground Beef", 300, "g"), ("Onion", 2, "pcs"), ("Egg", 1, "pcs"),
         ("Vegetable Oil", 30, "ml"), ("Salt", 1.5, "tsp"), ("Black Pepper", 0.5, "tsp"),
         ("Vinegar", 1, "tbsp"), ("Parsley", 1, "bunch")],
        [
            "Make a firm dough from flour, egg, water and salt; rest 30 minutes.",
            "Roll thin, cut into small squares and fill each with a bit of seasoned minced meat.",
            "Fold into triangles and press the edges firmly.",
            "Drop the chuchvara into boiling salted water in batches; cook until they float plus 2 minutes.",
            "Serve in the broth with a splash of vinegar and fresh parsley.",
        ],
    ),
    (
        "Shurpa (Hearty Meat Soup)",
        "uzbek-cuisine",
        120, 15, 6, "medium", 330, 22, 24, 15,
        [("Beef", 600, "g"), ("Potato", 4, "pcs"), ("Carrot", 2, "pcs"), ("Onion", 2, "pcs"),
         ("Tomato", 2, "pcs"), ("Chili Pepper", 1, "pcs"), ("Salt", 2, "tsp"), ("Bay Leaf", 2, "pcs"),
         ("Cilantro", 1, "bunch"), ("Water", 2500, "ml")],
        [
            "Place beef on the bone in cold water and bring to a simmer, skimming the foam.",
            "Add the whole onion and one carrot; simmer for 1 hour until the meat is tender.",
            "Add diced potatoes, carrot rounds, tomatoes and chili; cook 20 more minutes.",
            "Season with salt and bay leaves, then rest off the heat for 10 minutes.",
            "Serve in deep bowls topped with chopped cilantro.",
        ],
    ),
    (
        "Khanum (Steamed Rolls)",
        "uzbek-cuisine",
        30, 40, 5, "medium", 400, 20, 46, 14,
        [("Flour", 400, "g"), ("Ground Beef", 350, "g"), ("Onion", 3, "pcs"), ("Potato", 2, "pcs"),
         ("Salt", 1, "tsp"), ("Black Pepper", 0.5, "tsp"), ("Vegetable Oil", 30, "ml"), ("Tomato Paste", 1, "tbsp")],
        [
            "Knead a soft dough and roll it out into a large thin rectangle.",
            "Mix minced meat, grated potato and chopped onion; season well.",
            "Spread the filling over the dough and roll it into a tight spiral.",
            "Steam the roll for 30-35 minutes until cooked through.",
            "Slice into pieces and serve with a tomato-onion sauce.",
        ],
    ),
    (
        "Fluffy Omelette",
        "breakfast",
        10, 5, 2, "easy", 220, 13, 3, 17,
        [("Egg", 4, "pcs"), ("Milk", 100, "ml"), ("Butter", 20, "g"), ("Salt", 0.5, "tsp")],
        [
            "Whisk eggs with milk and salt until pale and foamy.",
            "Melt butter in a non-stick pan over medium-low heat.",
            "Pour in the egg mixture and cook gently, lifting the edges as it sets.",
            "Fold in half and slide onto a plate while still soft in the middle.",
        ],
    ),
    (
        "Baked Omelette with Ham and Cheese",
        "breakfast",
        25, 10, 4, "easy", 310, 22, 4, 23,
        [("Egg", 6, "pcs"), ("Cream", 100, "ml"), ("Cheddar Cheese", 100, "g"), ("Onion", 0.5, "pcs"),
         ("Bell Pepper", 1, "pcs"), ("Salt", 0.5, "tsp"), ("Black Pepper", 0.5, "tsp")],
        [
            "Whisk eggs and cream together with a pinch of salt.",
            "Fold in grated cheddar, diced pepper and onion.",
            "Pour into a greased baking dish and bake at 180В°C for 20-25 minutes.",
            "Cool 5 minutes, slice and serve.",
        ],
    ),
    (
        "Homemade Granola with Yogurt",
        "breakfast",
        25, 10, 4, "easy", 380, 12, 55, 12,
        [("Oats", 250, "g"), ("Honey", 80, "ml"), ("Walnuts", 60, "g"), ("Raisins", 50, "g"),
         ("Yogurt", 400, "g"), ("Strawberries", 200, "g"), ("Cinnamon", 0.5, "tsp")],
        [
            "Mix oats, chopped walnuts, cinnamon and honey; spread on a baking tray.",
            "Bake at 170В°C for 20 minutes, stirring once, until golden.",
            "Cool completely and stir through the raisins.",
            "Serve in bowls topped with yogurt and sliced strawberries.",
        ],
    ),
    (
        "Blueberry Pancakes",
        "breakfast",
        15, 15, 3, "easy", 330, 9, 48, 11,
        [("Flour", 250, "g"), ("Milk", 300, "ml"), ("Egg", 2, "pcs"), ("Sugar", 40, "g"),
         ("Baking Powder", 2, "tsp"), ("Blueberries", 150, "g"), ("Butter", 30, "g"), ("Salt", 0.25, "tsp")],
        [
            "Whisk eggs, milk and sugar; fold in flour and baking powder until just combined.",
            "Gently fold in the blueberries.",
            "Fry small ladles of batter on a buttered hot pan until bubbles form, then flip.",
            "Stack and serve with honey or maple syrup.",
        ],
    ),
    (
        "French Toast with Berries",
        "breakfast",
        12, 10, 2, "easy", 290, 9, 34, 13,
        [("Bread", 4, "pcs"), ("Egg", 2, "pcs"), ("Milk", 150, "ml"), ("Sugar", 25, "g"),
         ("Cinnamon", 0.5, "tsp"), ("Butter", 20, "g"), ("Strawberries", 100, "g")],
        [
            "Whisk eggs, milk, sugar and cinnamon in a shallow dish.",
            "Dip each bread slice in the mixture for a few seconds per side.",
            "Fry in butter over medium heat until golden on both sides.",
            "Top with fresh strawberries or blueberries.",
        ],
    ),
    (
        "Oatmeal Porridge with Apple",
        "breakfast",
        15, 5, 2, "easy", 250, 9, 45, 5,
        [("Oats", 100, "g"), ("Milk", 350, "ml"), ("Apple", 1, "pcs"), ("Honey", 2, "tbsp"),
         ("Cinnamon", 0.5, "tsp"), ("Walnuts", 20, "g")],
        [
            "Simmer oats and milk over low heat, stirring for 8-10 minutes.",
            "Stir in grated or diced apple and a pinch of cinnamon.",
            "Sweeten with honey and top with chopped walnuts.",
        ],
    ),
    (
        "Tomato Soup with Basil",
        "soups",
        35, 10, 4, "easy", 180, 4, 22, 9,
        [("Tomato", 800, "g"), ("Onion", 1, "pcs"), ("Garlic", 2, "pcs"), ("Olive Oil", 30, "ml"),
         ("Vegetable Oil", 1, "tbsp"), ("Cream", 100, "ml"), ("Sugar", 1, "tsp"), ("Salt", 1, "tsp"),
         ("Black Pepper", 0.5, "tsp")],
        [
            "Soften onion and garlic in olive oil until translucent.",
            "Add chopped tomatoes and simmer 20 minutes until broken down.",
            "Blend until smooth, then stir in cream and season with salt, pepper and sugar.",
            "Serve hot with a drizzle of olive oil.",
        ],
    ),
    (
        "Creamy Mushroom Soup",
        "soups",
        35, 15, 4, "easy", 240, 8, 14, 17,
        [("Mushroom", 400, "g"), ("Onion", 1, "pcs"), ("Garlic", 2, "pcs"), ("Milk", 300, "ml"),
         ("Butter", 40, "g"), ("Flour", 2, "tbsp"), ("Cream", 100, "ml"), ("Salt", 1, "tsp"),
         ("Black Pepper", 0.5, "tsp")],
        [
            "SautГ© sliced mushrooms with onion and garlic in butter until deeply browned.",
            "Sprinkle with flour and stir for a minute.",
            "Pour in milk gradually, then simmer 10 minutes.",
            "Blend half the soup and return it; stir in cream and season.",
        ],
    ),
    (
        "Borscht with Beef",
        "soups",
        90, 20, 6, "medium", 320, 18, 30, 14,
        [("Beef", 400, "g"), ("Beetroot", 3, "pcs"), ("Cabbage", 300, "g"), ("Potato", 3, "pcs"),
         ("Carrot", 1, "pcs"), ("Onion", 1, "pcs"), ("Tomato Paste", 2, "tbsp"), ("Vinegar", 1, "tbsp"),
         ("Sugar", 1, "tsp"), ("Salt", 2, "tsp"), ("Bay Leaf", 2, "pcs"), ("Sour Cream", 100, "g")],
        [
            "Simmer beef in 2 liters of water for 40 minutes to make the broth.",
            "SautГ© grated beetroot, carrot and onion with tomato paste, vinegar and sugar for 10 minutes.",
            "Add diced potatoes and shredded cabbage to the broth and cook 10 minutes.",
            "Stir in the beetroot mixture and simmer 10 more minutes with bay leaf.",
            "Serve with a generous spoon of sour cream.",
        ],
    ),
    (
        "Lentil Soup with Cumin",
        "soups",
        45, 10, 4, "easy", 260, 16, 36, 6,
        [("Lentils", 250, "g"), ("Carrot", 1, "pcs"), ("Onion", 1, "pcs"), ("Garlic", 2, "pcs"),
         ("Ground Cumin", 1, "tsp"), ("Tomato Paste", 1, "tbsp"), ("Olive Oil", 20, "ml"),
         ("Salt", 1, "tsp"), ("Vinegar", 1, "tbsp")],
        [
            "SautГ© onion, carrot and garlic in olive oil until soft.",
            "Stir in tomato paste and cumin, then add the rinsed lentils.",
            "Add 1.5 liters of water and simmer 30 minutes until the lentils collapse.",
            "Blend until creamy and season; serve with a splash of vinegar.",
        ],
    ),
    (
        "Minestrone Soup",
        "soups",
        50, 15, 6, "easy", 240, 10, 35, 7,
        [("Onion", 1, "pcs"), ("Carrot", 1, "pcs"), ("Celery", 2, "pcs"), ("Zucchini", 1, "pcs"),
         ("Green Beans", 100, "g"), ("Tomato", 2, "pcs"), ("Pasta", 100, "g"), ("Cabbage", 150, "g"),
         ("Olive Oil", 30, "ml"), ("Garlic", 2, "pcs"), ("Salt", 1.5, "tsp"), ("Parmesan", 40, "g")],
        [
            "Gently fry onion, carrot, celery and garlic in olive oil.",
            "Add zucchini, green beans, cabbage and chopped tomato; cook 10 minutes.",
            "Pour in 1.5 liters of water and simmer 30 minutes.",
            "Add pasta for the last 10 minutes until al dente.",
            "Serve topped with grated parmesan.",
        ],
    ),
    (
        "Classic Caesar Salad",
        "salads",
        15, 15, 2, "easy", 340, 18, 12, 25,
        [("Lettuce", 1, "pcs"), ("Chicken Breast", 200, "g"), ("Parmesan", 50, "g"), ("Bread", 3, "pcs"),
         ("Garlic", 1, "pcs"), ("Olive Oil", 40, "ml"), ("Mayonnaise", 40, "g"), ("Lemon", 0.5, "pcs"),
         ("Black Pepper", 0.5, "tsp")],
        [
            "Season and pan-fry the chicken breast until golden, then slice.",
            "Cube bread, toss with oil and bake into crunchy croutons.",
            "Whisk mayonnaise with lemon juice, grated garlic and pepper for the dressing.",
            "Tear lettuce into a bowl, add chicken and croutons, drizzle dressing and shave parmesan over.",
        ],
    ),
    (
        "Greek Salad",
        "salads",
        15, 10, 4, "easy", 250, 8, 10, 19,
        [("Tomato", 3, "pcs"), ("Cucumber", 1, "pcs"), ("Feta", 150, "g"), ("Onion", 0.5, "pcs"),
         ("Olive Oil", 30, "ml"), ("Lemon", 0.5, "pcs"), ("Oregano", 0.5, "tsp"), ("Salt", 0.5, "tsp")],
        [
            "Cut tomatoes, cucumber and onion into chunky pieces.",
            "Add blocks of feta cheese.",
            "Whisk olive oil, lemon juice, oregano and salt; pour over the salad.",
        ],
    ),
    (
        "Warm Potato Salad",
        "salads",
        25, 10, 4, "easy", 260, 6, 30, 13,
        [("Potato", 6, "pcs"), ("Dill", 1, "bunch"), ("Onion", 0.5, "pcs"), ("Vinegar", 2, "tbsp"),
         ("Olive Oil", 40, "ml"), ("Salt", 1, "tsp"), ("Black Pepper", 0.5, "tsp")],
        [
            "Boil potatoes in salted water until tender, then slice while warm.",
            "Whisk oil, vinegar, salt and pepper into a dressing.",
            "Toss potatoes with sliced onion and pour over the dressing.",
            "Sprinkle generously with fresh dill and serve warm.",
        ],
    ),
    (
        "Beetroot and Walnut Salad",
        "salads",
        45, 10, 4, "easy", 210, 5, 18, 14,
        [("Beetroot", 3, "pcs"), ("Walnuts", 60, "g"), ("Garlic", 1, "pcs"), ("Mayonnaise", 60, "g"),
         ("Salt", 0.5, "tsp"), ("Raisins", 30, "g")],
        [
            "Boil or roast whole beetroot until tender, then cool and grate coarsely.",
            "Toast the walnuts briefly in a dry pan.",
            "Combine beetroot, toasted walnuts, raisins, crushed garlic, mayonnaise and salt.",
            "Chill for 30 minutes before serving.",
        ],
    ),
    (
        "Fresh Cucumber and Tomato Salad",
        "salads",
        10, 10, 2, "easy", 90, 2, 8, 6,
        [("Cucumber", 2, "pcs"), ("Tomato", 2, "pcs"), ("Onion", 0.5, "pcs"), ("Olive Oil", 15, "ml"),
         ("Vinegar", 1, "tbsp"), ("Salt", 0.5, "tsp"), ("Parsley", 1, "bunch")],
        [
            "Slice cucumbers and tomatoes into rounds.",
            "Add thin onion half-rings and chopped parsley.",
            "Toss with oil, vinegar and salt; serve immediately.",
        ],
    ),
    (
        "Homemade Margherita Pizza",
        "fast_food",
        20, 30, 2, "medium", 480, 20, 60, 16,
        [("Pizza Dough", 300, "g"), ("Tomato Sauce", 150, "g"), ("Mozzarella", 150, "g"),
         ("Tomato", 1, "pcs"), ("Olive Oil", 15, "ml"), ("Basil", 1, "bunch"), ("Salt", 0.5, "tsp")],
        [
            "Preheat the oven to its highest setting (250В°C+) with a tray inside.",
            "Stretch the dough into a round and spread tomato sauce over it.",
            "Scatter sliced mozzarella and tomato, then drizzle with olive oil.",
            "Bake for 10-12 minutes until blistered and browned.",
            "Finish with fresh basil leaves.",
        ],
    ),
    (
        "Beef Burger with Caramelized Onion",
        "fast_food",
        20, 25, 4, "medium", 560, 28, 40, 30,
        [("Ground Beef", 500, "g"), ("Burger Buns", 4, "pcs"), ("Onion", 2, "pcs"), ("Cheddar Cheese", 80, "g"),
         ("Lettuce", 4, "pcs"), ("Tomato", 1, "pcs"), ("Ketchup", 40, "g"), ("Mayonnaise", 40, "g"),
         ("Salt", 1, "tsp"), ("Black Pepper", 0.5, "tsp")],
        [
            "Season the mince and shape into 4 patties, slightly wider than the buns.",
            "Slowly caramelize sliced onions in a pan for 10 minutes.",
            "Griddle the patties 3-4 minutes per side, topping with cheddar at the end.",
            "Toast the buns, layer with sauce, lettuce, tomato, patty and onions.",
        ],
    ),
    (
        "Chicken Shawarma",
        "fast_food",
        15, 20, 4, "medium", 430, 28, 30, 21,
        [("Chicken Thighs", 600, "g"), ("Lavash", 4, "pcs"), ("Yogurt", 100, "g"), ("Garlic", 2, "pcs"),
         ("Ground Cumin", 1, "tsp"), ("Paprika", 1, "tsp"), ("Lemon", 0.5, "pcs"), ("Cabbage", 200, "g"),
         ("Carrot", 1, "pcs"), ("Mayonnaise", 40, "g"), ("Ketchup", 40, "g")],
        [
            "Marinate chicken in yogurt, garlic, cumin, paprika and lemon for 30 minutes.",
            "Cook the chicken in a hot pan until charred and cooked through; slice thinly.",
            "Toss shredded cabbage and carrot with mayonnaise for the slaw.",
            "Warm the lavash, layer slaw, chicken and ketchup, then roll tightly and toast the seam.",
        ],
    ),
    (
        "Crunchy Falafel with Hummus",
        "fast_food",
        20, 30, 4, "medium", 380, 15, 45, 14,
        [("Chickpeas", 300, "g"), ("Onion", 1, "pcs"), ("Garlic", 3, "pcs"), ("Parsley", 1, "bunch"),
         ("Ground Cumin", 1, "tsp"), ("Ground Coriander", 1, "tsp"), ("Flour", 3, "tbsp"),
         ("Vegetable Oil", 500, "ml"), ("Salt", 1, "tsp"), ("Bread", 4, "pcs")],
        [
            "Blitz soaked chickpeas with onion, garlic, parsley and spices until coarse.",
            "Bind with flour, season and shape into small patties.",
            "Chill the patties 20 minutes so they hold together.",
            "Fry in hot oil until deep golden on both sides.",
            "Serve in pita-style bread with hummus and fresh salad.",
        ],
    ),
    (
        "Grilled Cheese Sandwich",
        "fast_food",
        8, 5, 1, "easy", 420, 14, 34, 25,
        [("Bread", 2, "pcs"), ("Cheddar Cheese", 80, "g"), ("Butter", 20, "g"), ("Tomato", 0.5, "pcs")],
        [
            "Butter one side of each bread slice.",
            "Fill the sandwich with grated cheddar and thin tomato slices.",
            "Toast in a hot pan 3 minutes per side until aggressively golden and melted.",
        ],
    ),
    (
        "BBQ Chicken Wings",
        "fast_food",
        30, 10, 4, "easy", 350, 26, 18, 18,
        [("Chicken Wings", 800, "g"), ("Honey", 3, "tbsp"), ("Soy Sauce", 3, "tbsp"), ("Garlic", 2, "pcs"),
         ("Paprika", 1, "tsp"), ("Ginger", 1, "tbsp"), ("Salt", 0.5, "tsp")],
        [
            "Whisk honey, soy, garlic, ginger and paprika into a glaze.",
            "Coat the wings and bake at 200В°C for 25 minutes, basting halfway.",
            "Finish under the grill until sticky and caramelized.",
        ],
    ),
    (
        "Spaghetti Bolognese",
        "dinner",
        45, 15, 4, "medium", 520, 26, 55, 20,
        [("Spaghetti", 400, "g"), ("Ground Beef", 400, "g"), ("Onion", 1, "pcs"), ("Carrot", 1, "pcs"),
         ("Celery", 1, "pcs"), ("Tomato Paste", 2, "tbsp"), ("Tomato", 3, "pcs"), ("Garlic", 2, "pcs"),
         ("Olive Oil", 30, "ml"), ("Red Wine", 100, "ml"), ("Parmesan", 40, "g")],
        [
            "Sweat onion, carrot and celery in olive oil until soft.",
            "Add beef and brown well, breaking it into fine crumbles.",
            "Stir in garlic, tomato paste, chopped tomatoes and wine; simmer 25 minutes.",
            "Cook spaghetti until al dente and toss with the sauce.",
            "Serve with grated parmesan.",
        ],
    ),
    (
        "Creamy Carbonara",
        "dinner",
        20, 10, 2, "medium", 590, 24, 60, 26,
        [("Spaghetti", 300, "g"), ("Bacon", 150, "g"), ("Egg", 3, "pcs"), ("Parmesan", 80, "g"),
         ("Black Pepper", 1, "tsp"), ("Garlic", 1, "pcs")],
        [
            "Cook spaghetti in well-salted water until al dente.",
            "Meanwhile render the bacon with garlic until crisp.",
            "Whisk eggs with grated parmesan and plenty of black pepper.",
            "Off the heat, toss hot pasta with the egg mixture and crispy bacon until creamy.",
        ],
    ),
    (
        "Pasta Primavera",
        "dinner",
        25, 15, 4, "easy", 380, 13, 52, 12,
        [("Pasta", 350, "g"), ("Zucchini", 1, "pcs"), ("Bell Pepper", 1, "pcs"), ("Broccoli", 150, "g"),
         ("Tomato", 2, "pcs"), ("Garlic", 2, "pcs"), ("Olive Oil", 30, "ml"), ("Parmesan", 40, "g"),
         ("Lemon", 0.5, "pcs"), ("Salt", 1, "tsp")],
        [
            "Boil pasta until al dente, reserving a cup of pasta water.",
            "SautГ© garlic, zucchini, pepper and broccoli in olive oil for 5 minutes.",
            "Add tomatoes and cook until just soft.",
            "Toss pasta with vegetables, a splash of pasta water, lemon zest and parmesan.",
        ],
    ),
    (
        "Butter Chicken",
        "dinner",
        35, 20, 4, "medium", 520, 32, 18, 34,
        [("Chicken Breast", 500, "g"), ("Yogurt", 150, "g"), ("Tomato", 5, "pcs"), ("Cream", 150, "ml"),
         ("Butter", 50, "g"), ("Garlic", 2, "pcs"), ("Ginger", 1, "tbsp"), ("Paprika", 1, "tsp"),
         ("Ground Cumin", 1, "tsp"), ("Turmeric", 0.5, "tsp"), ("Honey", 1, "tbsp"), ("Salt", 1, "tsp")],
        [
            "Marinate chicken cubes in yogurt, garlic, ginger and spices for 30 minutes.",
            "Sear the chicken in a hot pan until lightly charred.",
            "Blend the tomatoes into a smooth puree and simmer with butter for 10 minutes.",
            "Stir in cream, honey and the seared chicken; simmer 5 more minutes.",
            "Serve over rice with a drizzle of cream.",
        ],
    ),
    (
        "Chicken Curry with Rice",
        "dinner",
        40, 15, 4, "easy", 490, 28, 46, 18,
        [("Chicken Thighs", 600, "g"), ("Onion", 2, "pcs"), ("Garlic", 3, "pcs"), ("Ginger", 1, "tbsp"),
         ("Tomato", 3, "pcs"), ("Coconut Milk", 200, "ml"), ("Curry Powder", 2, "tbsp"), ("Rice", 300, "g"),
         ("Vegetable Oil", 30, "ml"), ("Salt", 1, "tsp")],
        [
            "SautГ© sliced onion in oil until very soft and brown.",
            "Add garlic, ginger and curry powder; toast for a minute.",
            "Add chicken and brown, then chopped tomatoes and coconut milk.",
            "Simmer 20 minutes until the chicken is tender and the sauce thickens.",
            "Serve with steamed rice.",
        ],
    ),
    (
        "Beef Stroganoff",
        "dinner",
        40, 15, 4, "medium", 480, 30, 22, 30,
        [("Beef", 500, "g"), ("Onion", 2, "pcs"), ("Mushroom", 250, "g"), ("Sour Cream", 200, "g"),
         ("Flour", 2, "tbsp"), ("Butter", 40, "g"), ("Beef Broth", 200, "ml"), ("Garlic", 1, "pcs"),
         ("Salt", 1, "tsp"), ("Black Pepper", 0.5, "tsp")],
        [
            "Sear beef strips quickly in butter until browned; set aside.",
            "SautГ© onion and mushrooms until deeply golden.",
            "Sprinkle with flour, add broth and simmer 5 minutes.",
            "Return the beef, stir in sour cream and warm through without boiling.",
            "Serve over pasta or mashed potatoes.",
        ],
    ),
    (
        "Roast Chicken with Potatoes",
        "dinner",
        80, 20, 6, "medium", 430, 32, 30, 19,
        [("Chicken", 1, "pcs"), ("Potato", 6, "pcs"), ("Garlic", 6, "pcs"), ("Lemon", 1, "pcs"),
         ("Paprika", 1, "tsp"), ("Olive Oil", 40, "ml"), ("Salt", 2, "tsp"), ("Rosemary", 1, "tbsp")],
        [
            "Pat the chicken dry and season generously inside and out.",
            "Stuff the cavity with lemon halves and garlic cloves.",
            "Toss potato wedges with oil, paprika and rosemary around the chicken.",
            "Roast at 200В°C for 70 minutes, resting 10 minutes before carving.",
        ],
    ),
    (
        "Chicken Rice (One Pot)",
        "dinner",
        45, 15, 4, "easy", 470, 26, 44, 19,
        [("Chicken", 500, "g"), ("Rice", 350, "g"), ("Onion", 1, "pcs"), ("Carrot", 1, "pcs"),
         ("Garlic", 2, "pcs"), ("Chicken Broth", 700, "ml"), ("Turmeric", 0.5, "tsp"), ("Vegetable Oil", 30, "ml"),
         ("Salt", 1, "tsp"), ("Black Pepper", 0.5, "tsp")],
        [
            "Brown the chicken pieces well in a deep pan.",
            "Add onion, carrot and garlic; cook 5 minutes.",
            "Stir in rice and turmeric until glossy.",
            "Pour in broth, cover and simmer 20 minutes without stirring.",
            "Rest off the heat for 5 minutes, fluff and serve.",
        ],
    ),
    (
        "Stuffed Bell Peppers",
        "dinner",
        50, 20, 4, "medium", 420, 22, 38, 19,
        [("Bell Pepper", 4, "pcs"), ("Rice", 150, "g"), ("Ground Beef", 300, "g"), ("Onion", 1, "pcs"),
         ("Carrot", 1, "pcs"), ("Tomato", 2, "pcs"), ("Tomato Paste", 1, "tbsp"), ("Vegetable Oil", 20, "ml"),
         ("Salt", 1, "tsp"), ("Cilantro", 1, "bunch")],
        [
            "SautГ© onion, carrot and mince; stir in rice, tomato and cilantro and season.",
            "Cut the tops from the peppers and remove the seeds.",
            "Stuff the peppers firmly with the filling.",
            "Place in a pot, add tomato paste mixed with water, and simmer 40 minutes.",
        ],
    ),
    (
        "Ratatouille",
        "dinner",
        35, 20, 4, "easy", 180, 4, 20, 10,
        [("Eggplant", 1, "pcs"), ("Zucchini", 2, "pcs"), ("Bell Pepper", 2, "pcs"), ("Tomato", 4, "pcs"),
         ("Onion", 1, "pcs"), ("Garlic", 3, "pcs"), ("Olive Oil", 40, "ml"), ("Basil", 1, "bunch"),
         ("Salt", 1, "tsp"), ("Thyme", 1, "tsp")],
        [
            "Sweat onion and garlic in olive oil until soft.",
            "Add the vegetables in batches, cooking each until glossy.",
            "Season with salt and thyme; simmer 15 minutes until everything comes together.",
            "Finish with torn basil leaves.",
        ],
    ),
    (
        "Beef Stew with Vegetables",
        "dinner",
        120, 20, 6, "medium", 410, 26, 28, 21,
        [("Beef", 800, "g"), ("Potato", 4, "pcs"), ("Carrot", 2, "pcs"), ("Onion", 2, "pcs"),
         ("Flour", 3, "tbsp"), ("Tomato Paste", 2, "tbsp"), ("Beef Broth", 800, "ml"), ("Garlic", 3, "pcs"),
         ("Bay Leaf", 2, "pcs"), ("Salt", 2, "tsp"), ("Black Pepper", 1, "tsp")],
        [
            "Dust beef chunks in flour and brown in batches in hot oil.",
            "SautГ© onions until soft; add garlic and tomato paste.",
            "Return the beef, add broth, bay leaf and seasoning; simmer 60 minutes.",
            "Add carrots, then potatoes; cook a further 30 minutes until tender.",
        ],
    ),
    (
        "Grilled Salmon with Lemon",
        "seafood",
        18, 10, 2, "easy", 320, 30, 4, 20,
        [("Salmon", 400, "g"), ("Lemon", 1, "pcs"), ("Olive Oil", 20, "ml"), ("Garlic", 1, "pcs"),
         ("Salt", 0.5, "tsp"), ("Black Pepper", 0.5, "tsp"), ("Dill", 1, "bunch")],
        [
            "Rub salmon fillets with oil, lemon zest, garlic, salt and pepper.",
            "Grill 4-5 minutes per side until just opaque in the center.",
            "Squeeze lemon juice over and scatter with fresh dill.",
        ],
    ),
    (
        "Fish and Chips",
        "seafood",
        35, 20, 4, "medium", 620, 22, 58, 32,
        [("White Fish Fillet", 600, "g"), ("Potato", 6, "pcs"), ("Flour", 150, "g"), ("Egg", 2, "pcs"),
         ("Breadcrumbs", 120, "g"), ("Lemon", 1, "pcs"), ("Vegetable Oil", 500, "ml"), ("Salt", 1, "tsp")],
        [
            "Cut potatoes into thick chips and par-fry until pale, then drain.",
            "Coat fish fillets in flour, beaten egg and breadcrumbs.",
            "Fry the chips until golden and crispy.",
            "Fry the fish 4-5 minutes until golden and cooked through.",
            "Serve with lemon wedges and salt.",
        ],
    ),
    (
        "Shrimp Pasta with Garlic",
        "seafood",
        25, 10, 3, "easy", 480, 26, 48, 18,
        [("Spaghetti", 350, "g"), ("Shrimp", 400, "g"), ("Garlic", 4, "pcs"), ("Olive Oil", 40, "ml"),
         ("Chili Pepper", 1, "pcs"), ("Parsley", 1, "bunch"), ("Lemon", 0.5, "pcs"), ("Salt", 1, "tsp")],
        [
            "Cook spaghetti in salted water until al dente.",
            "SautГ© sliced garlic and chili in olive oil for 1 minute.",
            "Add the shrimp and cook until just pink.",
            "Toss in the pasta with a splash of pasta water, parsley and lemon.",
        ],
    ),
    (
        "Fluffy Mashed Potatoes",
        "dinner",
        25, 10, 4, "easy", 220, 4, 24, 12,
        [("Potato", 8, "pcs"), ("Butter", 60, "g"), ("Milk", 150, "ml"), ("Salt", 1.5, "tsp"),
         ("Black Pepper", 0.5, "tsp")],
        [
            "Boil peeled potatoes in salted water until very tender.",
            "Drain well and mash until smooth.",
            "Beat in butter and warm milk, then season.",
            "Whip until light and fluffy.",
        ],
    ),
    (
        "Crispy Baked Potato Wedges",
        "dinner",
        40, 10, 4, "easy", 230, 4, 36, 8,
        [("Potato", 6, "pcs"), ("Vegetable Oil", 30, "ml"), ("Paprika", 1, "tsp"), ("Garlic", 1, "tsp"),
         ("Salt", 1, "tsp"), ("Black Pepper", 0.5, "tsp")],
        [
            "Cut potatoes into wedges and soak in cold water 10 minutes; dry well.",
            "Toss with oil, paprika, garlic powder, salt and pepper.",
            "Spread on a tray and bake at 220В°C for 35-40 minutes, turning once.",
        ],
    ),
    (
        "Vegetable Stir-Fry",
        "dinner",
        15, 15, 2, "easy", 200, 6, 25, 9,
        [("Broccoli", 150, "g"), ("Bell Pepper", 1, "pcs"), ("Carrot", 1, "pcs"), ("Zucchini", 1, "pcs"),
         ("Mushroom", 100, "g"), ("Soy Sauce", 3, "tbsp"), ("Garlic", 2, "pcs"), ("Ginger", 1, "tbsp"),
         ("Vegetable Oil", 30, "ml"), ("Sesame Seeds", 1, "tbsp")],
        [
            "Heat oil until shimmering and stir-fry garlic and ginger.",
            "Add the hardest vegetables first (carrot, broccoli), then peppers and mushrooms.",
            "Splash in soy sauce and stir-fry 2 minutes until glossy.",
            "Finish with sesame seeds.",
        ],
    ),
    (
        "Spanish Omelette (Tortilla)",
        "breakfast",
        25, 15, 4, "medium", 320, 12, 18, 21,
        [("Egg", 6, "pcs"), ("Potato", 4, "pcs"), ("Onion", 1, "pcs"), ("Olive Oil", 60, "ml"),
         ("Salt", 1, "tsp")],
        [
            "Slowly cook sliced potatoes and onion in olive oil until soft but not brown.",
            "Beat the eggs, season and fold in the potatoes.",
            "Pour into a hot oiled pan and cook on low until mostly set.",
            "Flip onto a plate, slide back in and finish the other side.",
        ],
    ),
    (
        "Shakshuka (Eggs in Tomato Sauce)",
        "breakfast",
        25, 10, 2, "easy", 280, 15, 14, 18,
        [("Egg", 4, "pcs"), ("Tomato", 4, "pcs"), ("Onion", 1, "pcs"), ("Bell Pepper", 1, "pcs"),
         ("Garlic", 2, "pcs"), ("Paprika", 1, "tsp"), ("Ground Cumin", 0.5, "tsp"), ("Olive Oil", 30, "ml"),
         ("Salt", 1, "tsp"), ("Parsley", 1, "bunch")],
        [
            "SautГ© onion and pepper in olive oil until soft.",
            "Add garlic, paprika, cumin and chopped tomato; simmer 10 minutes.",
            "Make wells and crack in the eggs; cover and cook until the whites set.",
            "Scatter with parsley and serve with bread.",
        ],
    ),
    (
        "Chocolate Cake",
        "desserts",
        35, 20, 8, "medium", 460, 6, 55, 24,
        [("Flour", 200, "g"), ("Sugar", 200, "g"), ("Cocoa Powder", 60, "g"), ("Butter", 150, "g"),
         ("Egg", 3, "pcs"), ("Milk", 150, "ml"), ("Baking Powder", 2, "tsp"), ("Vanilla Extract", 1, "tsp")],
        [
            "Cream butter and sugar until pale, then beat in the eggs.",
            "Fold in flour, cocoa and baking powder alternately with milk.",
            "Bake at 180В°C for 30-35 minutes until a skewer comes out clean.",
            "Cool and dust with cocoa or frost as desired.",
        ],
    ),
    (
        "Apple Pie",
        "desserts",
        50, 30, 8, "medium", 380, 4, 52, 18,
        [("Flour", 300, "g"), ("Butter", 150, "g"), ("Sugar", 150, "g"), ("Apple", 6, "pcs"),
         ("Cinnamon", 2, "tsp"), ("Egg", 1, "pcs"), ("Lemon", 0.5, "pcs"), ("Salt", 0.25, "tsp")],
        [
            "Rub butter into flour, add a little sugar and water to form a chilled dough.",
            "Toss sliced apples with sugar, cinnamon and lemon juice.",
            "Line a tin with dough, fill with apples and cover with a top crust.",
            "Brush with egg and bake at 190В°C for 45-50 minutes until golden.",
        ],
    ),
    (
        "Classic Tiramisu",
        "desserts",
        30, 30, 8, "medium", 420, 8, 38, 26,
        [("Heavy Cream", 300, "ml"), ("Cream Cheese", 250, "g"), ("Sugar", 100, "g"), ("Espresso", 250, "ml"),
         ("Cocoa Powder", 30, "g"), ("Vanilla Extract", 1, "tsp"), ("Savoiardi Biscuits", 1, "pcs")],
        [
            "Whip heavy cream with sugar until soft peaks form.",
            "Fold in the cream cheese and vanilla until smooth.",
            "Dip sponge-style savoiardi biscuits in espresso.",
            "Layer biscuits and cream, finishing with cream; dust heavily with cocoa.",
        ],
    ),
    (
        "New York Cheesecake",
        "desserts",
        70, 30, 8, "hard", 480, 9, 36, 33,
        [("Cream Cheese", 600, "g"), ("Sugar", 180, "g"), ("Egg", 3, "pcs"), ("Heavy Cream", 200, "ml"),
         ("Butter", 80, "g"), ("Flour", 100, "g"), ("Salt", 0.25, "tsp"), ("Lemon", 0.5, "pcs")],
        [
            "Press a buttery shortbread base into a springform tin and chill.",
            "Beat cream cheese and sugar until smooth, then beat in eggs one at a time.",
            "Fold in cream and lemon zest; pour over the base.",
            "Bake at 160В°C for 60 minutes, then cool slowly in the oven.",
            "Chill overnight before slicing.",
        ],
    ),
    (
        "Banana Bread",
        "desserts",
        60, 15, 8, "easy", 340, 6, 48, 14,
        [("Banana", 3, "pcs"), ("Flour", 250, "g"), ("Sugar", 150, "g"), ("Butter", 100, "g"),
         ("Egg", 2, "pcs"), ("Baking Powder", 1, "tsp"), ("Walnuts", 60, "g"), ("Cinnamon", 1, "tsp")],
        [
            "Mash bananas and beat with melted butter, sugar and eggs.",
            "Fold in flour, baking powder, cinnamon and walnuts.",
            "Pour into a lined loaf tin and bake at 170В°C for 55 minutes.",
            "Cool before slicing to keep it moist.",
        ],
    ),
    (
        "Baked Cheesecake with Cream Cheese",
        "desserts",
        60, 20, 8, "medium", 460, 9, 34, 31,
        [("Cream Cheese", 500, "g"), ("Yogurt", 150, "g"), ("Sugar", 150, "g"), ("Egg", 3, "pcs"),
         ("Flour", 50, "g"), ("Butter", 80, "g"), ("Vanilla Extract", 1, "tsp")],
        [
            "Cream the cheese with sugar and yogurt until smooth.",
            "Beat in eggs one at a time, then fold in flour and vanilla.",
            "Pour over a buttered base in a lined tin.",
            "Bake at 165В°C for 55 minutes; cool completely and refrigerate.",
        ],
    ),
    (
        "Strawberry Smoothie Bowl",
        "breakfast",
        10, 5, 2, "easy", 260, 8, 42, 8,
        [("Strawberries", 300, "g"), ("Banana", 1, "pcs"), ("Yogurt", 200, "g"), ("Honey", 1, "tbsp"),
         ("Oats", 40, "g"), ("Blueberries", 50, "g")],
        [
            "Blend strawberries, banana, yogurt and honey until thick.",
            "Pour into bowls and top with oats and blueberries.",
        ],
    ),
    (
        "Hummus with Oven-Toasted Pita",
        "appetizers",
        15, 15, 4, "easy", 260, 10, 30, 11,
        [("Chickpeas", 300, "g"), ("Tahini", 3, "tbsp"), ("Lemon", 1, "pcs"), ("Garlic", 2, "pcs"),
         ("Olive Oil", 50, "ml"), ("Salt", 1, "tsp"), ("Paprika", 0.5, "tsp"), ("Bread", 4, "pcs")],
        [
            "Blend chickpeas, tahini, lemon, garlic and salt until silky.",
            "Loosen with ice water and olive oil to taste.",
            "Toast pita wedges in the oven until crisp.",
            "Serve hummus drizzled with oil and paprika.",
        ],
    ),
    (
        "Garlic Bread",
        "appetizers",
        12, 10, 4, "easy", 280, 7, 32, 14,
        [("Bread", 1, "pcs"), ("Butter", 80, "g"), ("Garlic", 4, "pcs"), ("Parsley", 1, "bunch"),
         ("Parmesan", 30, "g"), ("Salt", 0.25, "tsp")],
        [
            "Blend softened butter with crushed garlic, parsley and parmesan.",
            "Slice the baguette and spread the butter between the cuts.",
            "Bake at 200В°C for 8-10 minutes until crusty and golden.",
        ],
    ),
    (
        "Fresh Spring Rolls",
        "appetizers",
        20, 25, 4, "easy", 180, 8, 28, 4,
        [("Lettuce", 1, "pcs"), ("Carrot", 1, "pcs"), ("Cucumber", 1, "pcs"), ("Shrimp", 150, "g"),
         ("Noodles", 100, "g"), ("Mint", 1, "bunch"), ("Cilantro", 1, "bunch"), ("Soy Sauce", 3, "tbsp")],
        [
            "Soak rice paper wrappers in warm water until pliable.",
            "Layer lettuce, noodles, vegetables, shrimp and herbs in each wrapper.",
            "Roll tightly, tucking the ends as you go.",
            "Serve with soy sauce or a sweet chili dip.",
        ],
    ),
    (
        "Caesar Wrap with Grilled Chicken",
        "fast_food",
        20, 15, 2, "easy", 410, 26, 30, 20,
        [("Lavash", 2, "pcs"), ("Chicken Breast", 200, "g"), ("Lettuce", 1, "pcs"), ("Parmesan", 30, "g"),
         ("Mayonnaise", 40, "g"), ("Garlic", 1, "pcs"), ("Lemon", 0.5, "pcs"), ("Bread", 2, "pcs")],
        [
            "Grill and slice the chicken breast.",
            "Whisk mayo with garlic, lemon and grated parmesan.",
            "Toss lettuce with the dressing.",
            "Fill the lavash with lettuce, chicken and crispy bread croutons; roll tightly.",
        ],
    ),
    (
        "Quinoa Vegetable Bowl",
        "vegetarian",
        25, 15, 2, "easy", 350, 13, 44, 13,
        [("Couscous", 200, "g"), ("Avocado", 1, "pcs"), ("Tomato", 1, "pcs"), ("Cucumber", 1, "pcs"),
         ("Lemon", 0.5, "pcs"), ("Olive Oil", 20, "ml"), ("Feta", 60, "g"), ("Parsley", 1, "bunch")],
        [
            "Fluff the cooked couscous and cool slightly.",
            "Dice avocado, tomato and cucumber.",
            "Fold everything together with crumbled feta, lemon and olive oil.",
            "Scatter with parsley and serve.",
        ],
    ),
    (
        "Oven-Baked Fish Fillet with Vegetables",
        "seafood",
        35, 15, 3, "easy", 300, 26, 16, 14,
        [("White Fish Fillet", 500, "g"), ("Tomato", 2, "pcs"), ("Onion", 1, "pcs"), ("Lemon", 1, "pcs"),
         ("Olive Oil", 30, "ml"), ("Paprika", 1, "tsp"), ("Salt", 1, "tsp"), ("Dill", 1, "bunch")],
        [
            "Place fillets on a tray lined with parchment.",
            "Top with tomato slices, onion rings and lemon rounds.",
            "Season with oil, paprika, salt and dill.",
            "Bake at 190В°C for 25 minutes until the fish flakes.",
        ],
    ),
    (
        "Mushroom Carbonara",
        "fast_food",
        20, 10, 2, "easy", 540, 20, 52, 27,
        [("Spaghetti", 250, "g"), ("Mushroom", 250, "g"), ("Cream", 150, "ml"), ("Parmesan", 60, "g"),
         ("Garlic", 2, "pcs"), ("Olive Oil", 20, "ml"), ("Salt", 0.5, "tsp"), ("Black Pepper", 0.5, "tsp")],
        [
            "SautГ© mushrooms with garlic until golden.",
            "Pour in cream and simmer gently for 3 minutes.",
            "Toss with cooked spaghetti and finish with parmesan and pepper.",
        ],
    ),
    (
        "Buckwheat Porridge with Mushrooms",
        "dinner",
        30, 10, 4, "easy", 280, 9, 38, 10,
        [("Buckwheat", 300, "g"), ("Mushroom", 250, "g"), ("Onion", 1, "pcs"), ("Carrot", 1, "pcs"),
         ("Butter", 30, "g"), ("Vegetable Oil", 20, "ml"), ("Salt", 1, "tsp"), ("Water", 600, "ml")],
        [
            "SautГ© onion, carrot and mushrooms in a mix of butter and oil.",
            "Add the rinsed buckwheat and toast for 2 minutes.",
            "Pour in boiling water, season and simmer covered for 20 minutes.",
        ],
    ),
    (
        "Lavash Rolls with Chicken and Vegetables",
        "appetizers",
        15, 20, 4, "easy", 300, 18, 28, 12,
        [("Lavash", 2, "pcs"), ("Chicken Breast", 250, "g"), ("Cream Cheese", 100, "g"), ("Cucumber", 1, "pcs"),
         ("Bell Pepper", 1, "pcs"), ("Lettuce", 1, "pcs"), ("Salt", 0.5, "tsp")],
        [
            "Grill and slice the chicken into strips.",
            "Spread cream cheese over the lavash sheets.",
            "Layer lettuce, cucumber, pepper and chicken, then roll tightly.",
            "Chill 10 minutes before slicing into pinwheels.",
        ],
    ),
    (
        "Pumpkin Soup with Cinnamon",
        "soups",
        35, 15, 4, "easy", 210, 5, 30, 9,
        [("Pumpkin", 800, "g"), ("Onion", 1, "pcs"), ("Garlic", 2, "pcs"), ("Cream", 120, "ml"),
         ("Cinnamon", 0.5, "tsp"), ("Olive Oil", 20, "ml"), ("Salt", 1, "tsp"), ("Pumpkin Seeds", 20, "g")],
        [
            "SautГ© onion and garlic in olive oil, then add cubed pumpkin.",
            "Add water to cover and simmer 25 minutes until the pumpkin is soft.",
            "Blend with cream and cinnamon until silky.",
            "Serve with roasted pumpkin seeds.",
        ],
    ),
    (
        "Stir-Fried Noodles with Beef",
        "dinner",
        25, 15, 3, "easy", 460, 26, 52, 15,
        [("Noodles", 300, "g"), ("Beef", 300, "g"), ("Bell Pepper", 1, "pcs"), ("Carrot", 1, "pcs"),
         ("Onion", 1, "pcs"), ("Soy Sauce", 4, "tbsp"), ("Garlic", 2, "pcs"), ("Ginger", 1, "tbsp"),
         ("Vegetable Oil", 30, "ml")],
        [
            "Marinate beef strips in half the soy sauce for 10 minutes.",
            "Stir-fry the beef in a hot wok; set aside.",
            "Stir-fry vegetables with garlic and ginger.",
            "Add noodles and remaining soy, toss with the beef and serve.",
        ],
    ),
]

SEED_USERS = [
    ("admin@fintfood.dev", "FintFood Admin", "Admin@12345", True, True),
    ("asliddin@example.com", "Asliddin Karimov", "User@12345", False, False),
    ("madina@example.com", "Madina Yusupova", "User@12345", False, False),
    ("bekzod@example.com", "Bekzod Tursunov", "User@12345", False, False),
    ("nilufar@example.com", "Nilufar Ahmedova", "User@12345", False, False),
    ("doni@example.com", "Doni Smith", "User@12345", False, False),
]

REVIEW_COMMENTS = [
    "Absolutely loved it! Easy to follow and the whole family enjoyed it.",
    "Great recipe, made some minor tweaks and it turned out perfect.",
    "Tasty and simple. Will definitely make it again.",
    "This is now a staple in our house. The instructions are so clear.",
    "Good flavor, though I added a bit more seasoning to suit our taste.",
    "Beautiful dish! Took a bit longer than stated but worth the wait.",
    "The step-by-step guide made it foolproof for a beginner like me.",
    "Delicious and fresh. Perfect balance of ingredients.",
    "Rich, comforting and full of flavor. Highly recommend.",
    "Very good, but next time I will halve the cooking time.",
    "My guests were impressed! A keeper for sure.",
    "Simple ingredients, impressive result. Exactly what I needed.",
]
